const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync('web/app.js','utf8');
const start = source.indexOf('function renderProgress()');
const end = source.indexOf('function render()');
const elements = {};
const context = {activeJob:null,selectedCluster:'default',Date,$:id=>elements[id]||(elements[id]={querySelector:()=>elements.track||(elements.track={})})};
vm.createContext(context);
vm.runInContext(source.slice(start,end),context);
context.activeJob={cluster:'default',action:'create',state:'running',started:Date.now()/1000-65,log:'TASK [Wait for Rancher readiness] *****\n'};
context.$('health').textContent='На связи';
context.renderProgress();
assert.equal(elements.health.textContent,'Создаётся');
assert.equal(elements['operation-progress'].hidden,false);
assert.equal(elements['progress-title'].textContent,'Кластер создаётся');
assert.equal(elements['progress-stage'].textContent,'TASK [Wait for Rancher readiness]');
assert.equal(elements.track.hidden,false);
context.activeJob.state='success';context.renderProgress();
assert.equal(elements['progress-title'].textContent,'Операция завершена успешно');
assert.equal(elements.track.hidden,true);
context.activeJob.state='failed';context.renderProgress();
assert.match(elements['progress-title'].textContent,/ошибкой/);
context.selectedCluster='lab2';context.renderProgress();
assert.equal(elements['operation-progress'].hidden,true);
console.log('Progress tests passed: running beyond API readiness, success, failure, cluster scope.');
