apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pelmeni
resources:
  - resources.yaml
configMapGenerator:
  - name: pelmeni-page
    files:
      - site/index.html
      - site/pelmeni.jpg
